# GitHub workflow to enable continuous integratoin
name: Continuous Integration

# This workflow is triggered on pushes and pull requests to the repository.
on: 
  pull_request: 
    branches: 'master'

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-18.04, macos-10.15 ]
        cxx: [ g++-9, clang++ ]
        build_type: [ Debug, Release ]

    steps:
    - name: which CXX
      run: |
        which ${{matrix.cxx}} 
        ${{matrix.cxx}} --version
        which gfortran-9
    - uses: actions/checkout@v2
    - name: mkdir bin
      run: mkdir bin 
    - name: cmake
      run: cmake -D CMAKE_Fortran_COMPILER=`which gfortran-9` -D CMAKE_CXX_COMPILER=`which ${{matrix.cxx}}` -D CMAKE_BUILD_TYPE=${{matrix.build_type}} ..  
      working-directory: ./bin
    - name: make
      run: make
      working-directory: ./bin
    - name: ctest
      run: ctest -j2
      working-directory: ./bin
